version: '3.3'

networks:
    nginx-php-mysql-redis:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "80:80"
        volumes:
            - ./app:/var/www/project
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - nginx-php-mysql-redis
    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: php-container
        ports:
            - "9000:9000"
        volumes:
            - ./app:/var/www/project
            - ./docker/php/config/php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            - nginx-php-mysql-redis
    mysql:
        image: mysql:5.7
        container_name: mysql-container
        ports:
            - "4306:3306"
        volumes:
            - ./docker/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - nginx-php-mysql-redis
    redis:
        image: redis:4.0
        container_name: redis-container
        ports:
            - "6382:6379"
        networks:
            - nginx-php-mysql-redis